### ISSUE TITLE
Sinatra with Active Record: GET Requests Lab solution branch missing a deliverable

### ISSUE THREAD

**Issue by arnold805** [learn-co-curriculum/phase-3-sinatra-with-active-record-get-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/5180/assignments/180504?module_item_id=398459

### Concern

The solution branch seems to not include the method for the 'GET /baked_goods/most_expensive' lab deliverable.
I found that this worked for me:

  def self.most_expensive
    self.all.order(price: :desc).first
  end

### Suggested Changes

add this into baked_good.rb solution branch:

  def self.most_expensive
    self.all.order(price: :desc).first
  end

**Comment by AlveeM** [comment]
Hi, thank you for submitting this issue.

We've updated the `solution` branch with the the solution. The changes should be available on GitHub.

Thanks again for helping us improve the curriculum by pointing out the issue!
